# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: imml 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "imml"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = "2014-04-08"
  s.description = "immat\u{e9}riel.fr IMML parser/writer"
  s.email = "jboulnois@immateriel.fr"
  s.executables = ["imml_pp.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "bin/imml_pp.rb",
    "data/imml.rnc",
    "data/imml.rng",
    "data/imml.xsd",
    "data/imml_kit.rnc",
    "data/imml_kit.rng",
    "data/imml_kit.xsd",
    "lib/imml.rb",
    "lib/imml/book.rb",
    "lib/imml/header.rb",
    "lib/imml/order.rb"
  ]
  s.homepage = "http://github.com/immateriel/imml"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "immat\u{e9}riel.fr IMML parser/writer"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<levenshtein>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<levenshtein>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<levenshtein>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

