all:
	trang imml_kit.rng imml_kit.rnc
	trang imml_kit_201.rng imml_kit_201.rnc
	trang imml_kit_202.rng imml_kit_202.rnc
	trang store_check_extension.rng store_check_extension.rnc
	trang imml.rng imml.rnc
	